/**
 * pdf.js
 * Handles formal document compilation and browser print invocation for PDF export.
 */

function exportPlanPDF() {
  const plan = window.currentStartupPlan;
  if (!plan) {
    showToast("Please generate an operating plan first!", "info");
    return;
  }

  // Create print container
  const printContainer = document.createElement("div");
  printContainer.id = "plan-print-root";
  printContainer.className = "print-document";

  // Build Document HTML
  let htmlContent = `
    <div class="print-page cover-page">
      <div class="print-header-brand">
        <span class="brand-badge">Startup Operating Plan</span>
        <span class="brand-date">${new Date().toLocaleDateString()}</span>
      </div>
      <div class="cover-content">
        <h1>${plan.name}</h1>
        <p class="subtitle">Complete Operating Plan &amp; Launch Roadmap</p>
        <div class="meta-box">
          <div class="meta-item"><strong>Sector:</strong> <span>${plan.industry}</span></div>
          <div class="meta-item"><strong>Audience:</strong> <span>${plan.audience}</span></div>
          <div class="meta-item"><strong>Generated by:</strong> <span>Startup Copilot Intelligence</span></div>
        </div>
      </div>
      <div class="cover-footer">
        <p>CONFIDENTIAL &amp; PROPRIETARY</p>
      </div>
    </div>

    <div class="print-page">
      <h2>1. Executive Summary &amp; Strategy</h2>
      <div class="print-section">
        <h3>Value Proposition</h3>
        <p class="print-para">${plan.valProp}</p>
      </div>
      <div class="print-section">
        <h3>Ideal Customer Persona (ICP)</h3>
        <p class="print-para">${plan.icp}</p>
      </div>
      <div class="print-section">
        <h3>Validation Milestones</h3>
        <ul class="print-list">
          ${plan.validation.map(v => `<li>${v}</li>`).join("")}
        </ul>
      </div>
    </div>

    <div class="print-page">
      <h2>2. Market Sizing &amp; SWOT Analysis</h2>
      
      <div class="print-section">
        <h3>Market Sizing Estimates (TAM / SAM / SOM)</h3>
        <table class="print-table">
          <thead>
            <tr>
              <th>Segment</th>
              <th>Estimated Annual Valuation</th>
              <th>Description</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><strong>Total Addressable Market (TAM)</strong></td>
              <td>$${(plan.tam).toLocaleString()}M</td>
              <td>Global potential value if 100% market penetration is achieved.</td>
            </tr>
            <tr>
              <td><strong>Serviceable Addressable Market (SAM)</strong></td>
              <td>$${(plan.sam).toLocaleString()}M</td>
              <td>Your targeted operational/geographic segment of the TAM.</td>
            </tr>
            <tr>
              <td><strong>Serviceable Obtainable Market (SOM)</strong></td>
              <td>$${(plan.som).toLocaleString()}M</td>
              <td>Realistic target share capture within 2-3 years of launch.</td>
            </tr>
          </tbody>
        </table>
      </div>

      <div class="print-section">
        <h3>SWOT Analysis Matrix</h3>
        <div class="print-swot-grid">
          <div class="ps-box">
            <h4>Strengths</h4>
            <ul>${plan.swot.s.map(i => `<li>${i}</li>`).join("")}</ul>
          </div>
          <div class="ps-box">
            <h4>Weaknesses</h4>
            <ul>${plan.swot.w.map(i => `<li>${i}</li>`).join("")}</ul>
          </div>
          <div class="ps-box">
            <h4>Opportunities</h4>
            <ul>${plan.swot.o.map(i => `<li>${i}</li>`).join("")}</ul>
          </div>
          <div class="ps-box">
            <h4>Threats</h4>
            <ul>${plan.swot.t.map(i => `<li>${i}</li>`).join("")}</ul>
          </div>
        </div>
      </div>
    </div>

    <div class="print-page">
      <h2>3. Unit Economics &amp; Competitors</h2>
      
      <div class="print-section">
        <h3>Key Unit Economics (Projected)</h3>
        <table class="print-table">
          <thead>
            <tr>
              <th>Metric</th>
              <th>Value</th>
              <th>Operational Definition</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Average Contract Value / Pricing (ACV)</td>
              <td>$${plan.unitEconomics.price.toLocaleString()} / yr</td>
              <td>Estimated billing value per customer account per year.</td>
            </tr>
            <tr>
              <td>Customer Acquisition Cost (CAC)</td>
              <td>$${plan.unitEconomics.cac.toLocaleString()}</td>
              <td>Total marketing &amp; sales expense to win one customer.</td>
            </tr>
            <tr>
              <td>Customer Lifetime Value (LTV)</td>
              <td>$${(plan.unitEconomics.price / (plan.unitEconomics.churn / 100)).toLocaleString(undefined, {maximumFractionDigits: 0})}</td>
              <td>Cumulative revenue expected over customer lifecycle.</td>
            </tr>
            <tr>
              <td>LTV : CAC Leverage Ratio</td>
              <td>${((plan.unitEconomics.price / (plan.unitEconomics.churn / 100)) / plan.unitEconomics.cac).toFixed(1)}x</td>
              <td>Must exceed 3.0x to demonstrate scalable unit economics.</td>
            </tr>
          </tbody>
        </table>
      </div>

      <div class="print-section">
        <h3>Competitor Differentiation Matrix</h3>
        <table class="print-table">
          <thead>
            <tr>
              <th>Feature / Vector</th>
              <th>Your Startup (${plan.name})</th>
              ${plan.competitors.map(c => `<th>${c.name}</th>`).join("")}
            </tr>
          </thead>
          <tbody>
            ${plan.matrixRows.map(row => `
              <tr>
                <td><strong>${row[0]}</strong></td>
                <td>${row[1]}</td>
                ${plan.competitors.map((comp, cIdx) => `<td>${row[cIdx + 2] || ""}</td>`).join("")}
              </tr>
            `).join("")}
          </tbody>
        </table>
      </div>
    </div>

    <div class="print-page">
      <h2>4. 12-Week MVP Development Roadmap</h2>
      <p class="print-para">The timeline is divided into engineering, marketing, and operations checkpoints to manage resources optimally.</p>
      
      ${plan.roadmap.map(track => `
        <div class="print-section">
          <h3>Track: ${track.track}</h3>
          <table class="print-table">
            <thead>
              <tr>
                <th style="width: 120px;">Timeline</th>
                <th>Core Goal &amp; Task Deliverables</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>Weeks 1-3</strong></td>
                <td>${track.weeks[0]}</td>
              </tr>
              <tr>
                <td><strong>Weeks 4-6</strong></td>
                <td>${track.weeks[1]}</td>
              </tr>
              <tr>
                <td><strong>Weeks 7-9</strong></td>
                <td>${track.weeks[2]}</td>
              </tr>
              <tr>
                <td><strong>Weeks 10-12</strong></td>
                <td>${track.weeks[3]}</td>
              </tr>
            </tbody>
          </table>
        </div>
      `).join("")}
    </div>

    <div class="print-page">
      <h2>5. Funding Pathways &amp; Pitch deck</h2>
      
      <div class="print-section">
        <h3>Matched Capital Pathways</h3>
        <div class="print-funding-cards">
          ${plan.fundingPathways.map(pw => `
            <div class="print-fund-card ${pw.recommended ? 'rec' : ''}">
              <h4>${pw.name} ${pw.recommended ? '(Recommended)' : ''}</h4>
              <p><strong>Status:</strong> ${pw.match}</p>
              <p>${pw.desc}</p>
              <p><strong>Funding Capacity:</strong> ${pw.funding}</p>
            </div>
          `).join("")}
        </div>
      </div>

      <div class="print-section">
        <h3>10-Slide Investor Deck Structure</h3>
        <ol class="print-deck-list">
          ${plan.pitchDeck.map(slide => `
            <li>
              <strong>${slide.slide}</strong>
              <p>${slide.desc}</p>
            </li>
          `).join("")}
        </ol>
      </div>

      <div class="print-section">
        <h3>Matched Accelerators &amp; Government Grants</h3>
        <ul class="print-list">
          ${plan.grants.map(g => `
            <li>
              <strong>${g.name}</strong> - ${g.desc} (Link: ${g.link})
            </li>
          `).join("")}
        </ul>
      </div>
    </div>
  `;

  // Append styling for printing specifically
  const styleEl = document.createElement("style");
  styleEl.id = "plan-print-style";
  styleEl.innerHTML = `
    @media print {
      body * {
        visibility: hidden;
      }
      #plan-print-root, #plan-print-root * {
        visibility: visible;
      }
      #plan-print-root {
        position: absolute;
        left: 0;
        top: 0;
        width: 100%;
        color: #111827;
        background: #ffffff;
        font-family: 'Inter', sans-serif;
      }
      .print-page {
        page-break-after: always;
        padding: 2.5cm;
        min-height: 297mm; /* A4 height */
        box-sizing: border-box;
      }
      .cover-page {
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        height: 297mm;
      }
      .cover-content {
        margin-top: 5cm;
      }
      .cover-content h1 {
        font-size: 3.5rem;
        font-family: 'Outfit', sans-serif;
        color: #1e1b4b;
        margin-bottom: 10px;
        font-weight: 800;
      }
      .cover-content .subtitle {
        font-size: 1.5rem;
        color: #4b5563;
        margin-bottom: 3cm;
      }
      .meta-box {
        border-top: 2px solid #e5e7eb;
        padding-top: 1.5cm;
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: 10px;
      }
      .meta-item {
        font-size: 0.95rem;
        color: #374151;
      }
      .cover-footer {
        border-top: 1px solid #e5e7eb;
        padding-top: 10px;
        font-size: 0.8rem;
        color: #9ca3af;
        font-weight: 600;
        letter-spacing: 1px;
      }
      
      h2 {
        font-size: 1.8rem;
        font-family: 'Outfit', sans-serif;
        color: #1e1b4b;
        border-bottom: 2px solid #1e1b4b;
        padding-bottom: 8px;
        margin-bottom: 20px;
      }
      h3 {
        font-size: 1.15rem;
        color: #4f46e5;
        margin-top: 15px;
        margin-bottom: 10px;
        font-weight: 600;
      }
      .print-para {
        font-size: 0.9rem;
        line-height: 1.6;
        color: #374151;
        margin-bottom: 15px;
      }
      .print-list {
        padding-left: 20px;
        margin-bottom: 15px;
      }
      .print-list li {
        font-size: 0.9rem;
        line-height: 1.6;
        color: #374151;
        margin-bottom: 8px;
      }
      .print-table {
        width: 100%;
        border-collapse: collapse;
        margin-bottom: 25px;
      }
      .print-table th, .print-table td {
        border: 1px solid #e5e7eb;
        padding: 10px 12px;
        font-size: 0.85rem;
        text-align: left;
      }
      .print-table th {
        background-color: #f9fafb;
        color: #111827;
        font-weight: 600;
      }
      
      .print-swot-grid {
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: 15px;
      }
      .ps-box {
        border: 1px solid #e5e7eb;
        border-radius: 6px;
        padding: 12px;
        background-color: #f9fafb;
      }
      .ps-box h4 {
        font-size: 0.9rem;
        color: #1e1b4b;
        border-bottom: 1px solid #e5e7eb;
        padding-bottom: 5px;
        margin-bottom: 8px;
        text-transform: uppercase;
      }
      .ps-box ul {
        padding-left: 15px;
      }
      .ps-box li {
        font-size: 0.8rem;
        line-height: 1.4;
        color: #4b5563;
        margin-bottom: 4px;
      }

      .print-funding-cards {
        display: flex;
        flex-direction: column;
        gap: 15px;
      }
      .print-fund-card {
        border: 1px solid #e5e7eb;
        border-radius: 6px;
        padding: 15px;
      }
      .print-fund-card.rec {
        border-color: #4f46e5;
        background-color: #f5f3ff;
      }
      .print-fund-card h4 {
        margin-bottom: 5px;
      }
      .print-fund-card p {
        font-size: 0.85rem;
        margin-bottom: 5px;
        line-height: 1.4;
      }

      .print-deck-list {
        padding-left: 20px;
      }
      .print-deck-list li {
        margin-bottom: 12px;
        font-size: 0.85rem;
      }
      .print-deck-list p {
        color: #4b5563;
        margin-top: 3px;
      }
    }
  `;

  // Inject content & invoke print dialog
  printContainer.innerHTML = htmlContent;
  document.body.appendChild(printContainer);
  document.head.appendChild(styleEl);

  window.print();

  // Cleanup after printing triggers
  setTimeout(() => {
    document.body.removeChild(printContainer);
    document.head.removeChild(styleEl);
  }, 1000);
}

function exportStartupBriefPDF() {
  const plan = window.currentStartupPlan;
  if (!plan) {
    showToast("Please generate an operating plan first!", "info");
    return;
  }

  // Create print container
  const printContainer = document.createElement("div");
  printContainer.id = "plan-print-root";
  printContainer.className = "print-document";

  let warningBrief = "";
  if (plan.existingProblemDetected) {
    warningBrief = `
      <div class="print-section" style="border: 1px solid #f59e0b; padding: 12px; border-radius: 6px; background-color: #fffbeb; margin-bottom: 15px;">
        <h3 style="color: #d97706; margin-top: 0; font-size: 0.95rem; font-weight: 700;">Market Differentiation &amp; Pivot Strategy</h3>
        <p style="font-size: 0.8rem; line-height: 1.4; color: #78350f; margin: 0 0 8px 0;"><strong>Known Space:</strong> ${plan.detectedSpace}</p>
        <ul style="padding-left: 15px; margin: 0; font-size: 0.75rem; line-height: 1.4; color: #78350f;">
          ${plan.improvedSuggestions.map(s => `<li>${s}</li>`).join("")}
        </ul>
      </div>
    `;
  }

  // Build Document HTML
  let htmlContent = `
    <div class="print-page brief-page" style="padding: 1.5cm; font-family: 'Inter', sans-serif; color: #111827; background: #fff; min-height: 297mm; box-sizing: border-box; position: relative;">
      <div style="display: flex; justify-content: space-between; align-items: center; border-bottom: 2px solid #1e1b4b; padding-bottom: 8px; margin-bottom: 15px;">
        <div>
          <h1 style="margin: 0; font-size: 2rem; font-family: 'Outfit', sans-serif; color: #1e1b4b; font-weight: 800;">${plan.name}</h1>
          <p style="margin: 2px 0 0 0; font-size: 0.9rem; color: #4b5563;">Startup Executive Operating Brief</p>
        </div>
        <div style="text-align: right;">
          <span style="font-size: 0.75rem; color: #9ca3af; font-weight: 600; text-transform: uppercase; letter-spacing: 1px;">Startup Copilot</span>
          <p style="margin: 2px 0 0 0; font-size: 0.8rem; color: #4b5563;">${new Date().toLocaleDateString()}</p>
        </div>
      </div>

      <div style="display: grid; grid-template-columns: 1.5fr 1fr; gap: 15px; margin-bottom: 15px;">
        <div>
          <h3 style="color: #4f46e5; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; margin: 0 0 6px 0; font-size: 0.95rem;">Value Proposition</h3>
          <p style="font-size: 0.8rem; line-height: 1.4; color: #374151; margin: 0 0 12px 0;">${plan.valProp}</p>
          
          <h3 style="color: #4f46e5; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; margin: 0 0 6px 0; font-size: 0.95rem;">Ideal Customer Persona (ICP)</h3>
          <p style="font-size: 0.8rem; line-height: 1.4; color: #374151; margin: 0 0 12px 0;">${plan.icp}</p>
        </div>
        
        <div style="background-color: #f9fafb; padding: 12px; border-radius: 6px; border: 1px solid #e5e7eb; height: fit-content;">
          <h3 style="color: #1e1b4b; margin: 0 0 6px 0; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; font-size: 0.9rem;">Target Tech Stack</h3>
          <table style="width: 100%; border-collapse: collapse; font-size: 0.75rem;">
            <tbody>
              ${plan.customTechStack.map(s => `
                <tr style="border-bottom: 1px solid #f3f4f6;">
                  <td style="padding: 4px 0; font-weight: 600; color: #374151;">${s.type}</td>
                  <td style="padding: 4px 0; text-align: right; color: #4f46e5;">${s.name}</td>
                </tr>
              `).join("")}
            </tbody>
          </table>
        </div>
      </div>

      ${warningBrief}

      <div style="margin-bottom: 15px;">
        <h3 style="color: #4f46e5; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; margin: 0 0 6px 0; font-size: 0.95rem;">12-Week Launch Milestones</h3>
        <table style="width: 100%; border-collapse: collapse; font-size: 0.75rem;">
          <thead>
            <tr style="background-color: #f9fafb; border-bottom: 1px solid #e5e7eb;">
              <th style="padding: 6px; text-align: left; font-weight: 600; color: #111827;">Track</th>
              <th style="padding: 6px; text-align: left; font-weight: 600; color: #111827;">Weeks 1-3</th>
              <th style="padding: 6px; text-align: left; font-weight: 600; color: #111827;">Weeks 4-6</th>
              <th style="padding: 6px; text-align: left; font-weight: 600; color: #111827;">Weeks 7-9</th>
              <th style="padding: 6px; text-align: left; font-weight: 600; color: #111827;">Weeks 10-12</th>
            </tr>
          </thead>
          <tbody>
            ${plan.roadmap.map(track => `
              <tr style="border-bottom: 1px solid #e5e7eb;">
                <td style="padding: 6px; font-weight: 600; color: #374151;">${track.track}</td>
                <td style="padding: 6px; color: #4b5563; font-size: 0.7rem;">${track.weeks[0]}</td>
                <td style="padding: 6px; color: #4b5563; font-size: 0.7rem;">${track.weeks[1]}</td>
                <td style="padding: 6px; color: #4b5563; font-size: 0.7rem;">${track.weeks[2]}</td>
                <td style="padding: 6px; color: #4b5563; font-size: 0.7rem;">${track.weeks[3]}</td>
              </tr>
            `).join("")}
          </tbody>
        </table>
      </div>

      <div style="display: grid; grid-template-columns: 1.2fr 1fr; gap: 15px; margin-bottom: 40px;">
        <div>
          <h3 style="color: #4f46e5; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; margin: 0 0 6px 0; font-size: 0.95rem;">Strategic Validation Checkpoints</h3>
          <ul style="padding-left: 15px; margin: 0; font-size: 0.75rem; line-height: 1.4; color: #4b5563;">
            ${plan.validation.slice(0, 3).map(v => `<li>${v}</li>`).join("")}
          </ul>
        </div>
        <div>
          <h3 style="color: #4f46e5; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; margin: 0 0 6px 0; font-size: 0.95rem;">Key Economics &amp; Market</h3>
          <table style="width: 100%; border-collapse: collapse; font-size: 0.75rem;">
            <tbody>
              <tr style="border-bottom: 1px solid #f3f4f6;">
                <td style="padding: 4px 0; color: #4b5563;">Annual Price (ACV)</td>
                <td style="padding: 4px 0; text-align: right; font-weight: 600; color: #111827;">$${plan.unitEconomics.price.toLocaleString()}</td>
              </tr>
              <tr style="border-bottom: 1px solid #f3f4f6;">
                <td style="padding: 4px 0; color: #4b5563;">CAC</td>
                <td style="padding: 4px 0; text-align: right; font-weight: 600; color: #111827;">$${plan.unitEconomics.cac.toLocaleString()}</td>
              </tr>
              <tr style="border-bottom: 1px solid #f3f4f6;">
                <td style="padding: 4px 0; color: #4b5563;">TAM Sizing</td>
                <td style="padding: 4px 0; text-align: right; font-weight: 600; color: #111827;">$${plan.tam}M</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      
      <div style="position: absolute; bottom: 1cm; left: 1.5cm; right: 1.5cm; border-top: 1px solid #e5e7eb; padding-top: 6px; text-align: center; font-size: 0.7rem; color: #9ca3af; font-weight: 600; letter-spacing: 0.5px;">
        CONFIDENTIAL &amp; PROPRIETARY — GENERATED BY STARTUP COPILOT
      </div>
    </div>
  `;

  // Append styling for printing specifically
  const styleEl = document.createElement("style");
  styleEl.id = "plan-print-style";
  styleEl.innerHTML = `
    @media print {
      body * {
        visibility: hidden;
      }
      #plan-print-root, #plan-print-root * {
        visibility: visible;
      }
      #plan-print-root {
        position: absolute;
        left: 0;
        top: 0;
        width: 100%;
        color: #111827;
        background: #ffffff;
        font-family: 'Inter', sans-serif;
      }
    }
  `;

  // Inject content & invoke print dialog
  printContainer.innerHTML = htmlContent;
  document.body.appendChild(printContainer);
  document.head.appendChild(styleEl);

  window.print();

  // Cleanup after printing triggers
  setTimeout(() => {
    document.body.removeChild(printContainer);
    document.head.removeChild(styleEl);
  }, 1000);
}

